/* automatically generated by rust-bindgen 0.72.1 */

pub const LGW_COM_SUCCESS: u32 = 0;
pub const LGW_COM_ERROR: i32 = -1;
pub const LGW_SPI_MUX_TARGET_SX1302: u32 = 0;
pub const LGW_SPI_MUX_TARGET_RADIOA: u32 = 1;
pub const LGW_SPI_MUX_TARGET_RADIOB: u32 = 2;
pub const LGW_HAL_SUCCESS: u32 = 0;
pub const LGW_HAL_ERROR: i32 = -1;
pub const LGW_LBT_NOT_ALLOWED: u32 = 1;
pub const LGW_XTAL_FREQU: u32 = 32000000;
pub const LGW_RF_CHAIN_NB: u32 = 2;
pub const LGW_IF_CHAIN_NB: u32 = 10;
pub const LGW_REF_BW: u32 = 125000;
pub const LGW_MULTI_NB: u32 = 8;
pub const LGW_MULTI_SF_EN: u32 = 255;
pub const LGW_LBT_CHANNEL_NB_MAX: u32 = 16;
pub const LGW_SPECTRAL_SCAN_RESULT_SIZE: u32 = 33;
pub const com_type_e_LGW_COM_SPI: com_type_e = 0;
pub const com_type_e_LGW_COM_USB: com_type_e = 1;
pub const com_type_e_LGW_COM_UNKNOWN: com_type_e = 2;
pub type com_type_e = ::std::os::raw::c_uint;
pub use self::com_type_e as lgw_com_type_t;
pub const com_write_mode_e_LGW_COM_WRITE_MODE_SINGLE: com_write_mode_e = 0;
pub const com_write_mode_e_LGW_COM_WRITE_MODE_BULK: com_write_mode_e = 1;
pub const com_write_mode_e_LGW_COM_WRITE_MODE_UNKNOWN: com_write_mode_e = 2;
pub type com_write_mode_e = ::std::os::raw::c_uint;
pub use self::com_write_mode_e as lgw_com_write_mode_t;
unsafe extern "C" {
    pub fn lgw_com_open(
        com_type: lgw_com_type_t,
        com_path: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lgw_com_close() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lgw_com_w(spi_mux_target: u8, address: u16, data: u8) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lgw_com_r(spi_mux_target: u8, address: u16, data: *mut u8) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lgw_com_rmw(
        spi_mux_target: u8,
        address: u16,
        offs: u8,
        leng: u8,
        data: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lgw_com_wb(
        spi_mux_target: u8,
        address: u16,
        data: *const u8,
        size: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lgw_com_rb(
        spi_mux_target: u8,
        address: u16,
        data: *mut u8,
        size: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lgw_com_set_write_mode(write_mode: lgw_com_write_mode_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lgw_com_flush() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lgw_com_chunk_size() -> u16;
}
unsafe extern "C" {
    pub fn lgw_com_get_temperature(temperature: *mut f32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lgw_com_target() -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn lgw_com_type() -> lgw_com_type_t;
}
pub const lgw_radio_type_t_LGW_RADIO_TYPE_NONE: lgw_radio_type_t = 0;
pub const lgw_radio_type_t_LGW_RADIO_TYPE_SX1255: lgw_radio_type_t = 1;
pub const lgw_radio_type_t_LGW_RADIO_TYPE_SX1257: lgw_radio_type_t = 2;
pub const lgw_radio_type_t_LGW_RADIO_TYPE_SX1272: lgw_radio_type_t = 3;
pub const lgw_radio_type_t_LGW_RADIO_TYPE_SX1276: lgw_radio_type_t = 4;
pub const lgw_radio_type_t_LGW_RADIO_TYPE_SX1250: lgw_radio_type_t = 5;
#[doc = "@enum lgw_radio_type_t\n@brief Radio types that can be found on the LoRa Gateway"]
pub type lgw_radio_type_t = ::std::os::raw::c_uint;
#[doc = "@struct lgw_conf_board_s\n@brief Configuration structure for board specificities"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_conf_board_s {
    pub lorawan_public: bool,
    #[doc = "> Enable ONLY for *public* networks using the LoRa MAC protocol"]
    pub clksrc: u8,
    #[doc = "> Index of RF chain which provides clock to concentrator"]
    pub full_duplex: bool,
    #[doc = "> Indicates if the gateway operates in full duplex mode or not"]
    pub com_type: lgw_com_type_t,
    #[doc = "> The COMmunication interface (SPI/USB) to connect to the SX1302"]
    pub com_path: [::std::os::raw::c_char; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_conf_board_s"][::std::mem::size_of::<lgw_conf_board_s>() - 72usize];
    ["Alignment of lgw_conf_board_s"][::std::mem::align_of::<lgw_conf_board_s>() - 4usize];
    ["Offset of field: lgw_conf_board_s::lorawan_public"]
        [::std::mem::offset_of!(lgw_conf_board_s, lorawan_public) - 0usize];
    ["Offset of field: lgw_conf_board_s::clksrc"]
        [::std::mem::offset_of!(lgw_conf_board_s, clksrc) - 1usize];
    ["Offset of field: lgw_conf_board_s::full_duplex"]
        [::std::mem::offset_of!(lgw_conf_board_s, full_duplex) - 2usize];
    ["Offset of field: lgw_conf_board_s::com_type"]
        [::std::mem::offset_of!(lgw_conf_board_s, com_type) - 4usize];
    ["Offset of field: lgw_conf_board_s::com_path"]
        [::std::mem::offset_of!(lgw_conf_board_s, com_path) - 8usize];
};
#[doc = "@struct lgw_rssi_tcomp_s\n@brief Structure containing all coefficients necessary to compute the offset to be applied on RSSI for current temperature"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_rssi_tcomp_s {
    pub coeff_a: f32,
    pub coeff_b: f32,
    pub coeff_c: f32,
    pub coeff_d: f32,
    pub coeff_e: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_rssi_tcomp_s"][::std::mem::size_of::<lgw_rssi_tcomp_s>() - 20usize];
    ["Alignment of lgw_rssi_tcomp_s"][::std::mem::align_of::<lgw_rssi_tcomp_s>() - 4usize];
    ["Offset of field: lgw_rssi_tcomp_s::coeff_a"]
        [::std::mem::offset_of!(lgw_rssi_tcomp_s, coeff_a) - 0usize];
    ["Offset of field: lgw_rssi_tcomp_s::coeff_b"]
        [::std::mem::offset_of!(lgw_rssi_tcomp_s, coeff_b) - 4usize];
    ["Offset of field: lgw_rssi_tcomp_s::coeff_c"]
        [::std::mem::offset_of!(lgw_rssi_tcomp_s, coeff_c) - 8usize];
    ["Offset of field: lgw_rssi_tcomp_s::coeff_d"]
        [::std::mem::offset_of!(lgw_rssi_tcomp_s, coeff_d) - 12usize];
    ["Offset of field: lgw_rssi_tcomp_s::coeff_e"]
        [::std::mem::offset_of!(lgw_rssi_tcomp_s, coeff_e) - 16usize];
};
#[doc = "@struct lgw_conf_rxrf_s\n@brief Configuration structure for a RF chain"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_conf_rxrf_s {
    pub enable: bool,
    #[doc = "> enable or disable that RF chain"]
    pub freq_hz: u32,
    #[doc = "> center frequency of the radio in Hz"]
    pub rssi_offset: f32,
    #[doc = "> Board-specific RSSI correction factor"]
    pub rssi_tcomp: lgw_rssi_tcomp_s,
    #[doc = "> Board-specific RSSI temperature compensation coefficients"]
    pub type_: lgw_radio_type_t,
    #[doc = "> Radio type for that RF chain (SX1255, SX1257....)"]
    pub tx_enable: bool,
    #[doc = "> enable or disable TX on that RF chain"]
    pub single_input_mode: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_conf_rxrf_s"][::std::mem::size_of::<lgw_conf_rxrf_s>() - 40usize];
    ["Alignment of lgw_conf_rxrf_s"][::std::mem::align_of::<lgw_conf_rxrf_s>() - 4usize];
    ["Offset of field: lgw_conf_rxrf_s::enable"]
        [::std::mem::offset_of!(lgw_conf_rxrf_s, enable) - 0usize];
    ["Offset of field: lgw_conf_rxrf_s::freq_hz"]
        [::std::mem::offset_of!(lgw_conf_rxrf_s, freq_hz) - 4usize];
    ["Offset of field: lgw_conf_rxrf_s::rssi_offset"]
        [::std::mem::offset_of!(lgw_conf_rxrf_s, rssi_offset) - 8usize];
    ["Offset of field: lgw_conf_rxrf_s::rssi_tcomp"]
        [::std::mem::offset_of!(lgw_conf_rxrf_s, rssi_tcomp) - 12usize];
    ["Offset of field: lgw_conf_rxrf_s::type_"]
        [::std::mem::offset_of!(lgw_conf_rxrf_s, type_) - 32usize];
    ["Offset of field: lgw_conf_rxrf_s::tx_enable"]
        [::std::mem::offset_of!(lgw_conf_rxrf_s, tx_enable) - 36usize];
    ["Offset of field: lgw_conf_rxrf_s::single_input_mode"]
        [::std::mem::offset_of!(lgw_conf_rxrf_s, single_input_mode) - 37usize];
};
#[doc = "@struct lgw_conf_rxif_s\n@brief Configuration structure for an IF chain"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_conf_rxif_s {
    pub enable: bool,
    #[doc = "> enable or disable that IF chain"]
    pub rf_chain: u8,
    #[doc = "> to which RF chain is that IF chain associated"]
    pub freq_hz: i32,
    #[doc = "> center frequ of the IF chain, relative to RF chain frequency"]
    pub bandwidth: u8,
    #[doc = "> RX bandwidth, 0 for default"]
    pub datarate: u32,
    #[doc = "> RX datarate, 0 for default"]
    pub sync_word_size: u8,
    #[doc = "> size of FSK sync word (number of bytes, 0 for default)"]
    pub sync_word: u64,
    #[doc = "> FSK sync word (ALIGN RIGHT, eg. 0xC194C1)"]
    pub implicit_hdr: bool,
    #[doc = "> LoRa Service implicit header"]
    pub implicit_payload_length: u8,
    #[doc = "> LoRa Service implicit header payload length (number of bytes, 0 for default)"]
    pub implicit_crc_en: bool,
    #[doc = "> LoRa Service implicit header CRC enable"]
    pub implicit_coderate: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_conf_rxif_s"][::std::mem::size_of::<lgw_conf_rxif_s>() - 40usize];
    ["Alignment of lgw_conf_rxif_s"][::std::mem::align_of::<lgw_conf_rxif_s>() - 8usize];
    ["Offset of field: lgw_conf_rxif_s::enable"]
        [::std::mem::offset_of!(lgw_conf_rxif_s, enable) - 0usize];
    ["Offset of field: lgw_conf_rxif_s::rf_chain"]
        [::std::mem::offset_of!(lgw_conf_rxif_s, rf_chain) - 1usize];
    ["Offset of field: lgw_conf_rxif_s::freq_hz"]
        [::std::mem::offset_of!(lgw_conf_rxif_s, freq_hz) - 4usize];
    ["Offset of field: lgw_conf_rxif_s::bandwidth"]
        [::std::mem::offset_of!(lgw_conf_rxif_s, bandwidth) - 8usize];
    ["Offset of field: lgw_conf_rxif_s::datarate"]
        [::std::mem::offset_of!(lgw_conf_rxif_s, datarate) - 12usize];
    ["Offset of field: lgw_conf_rxif_s::sync_word_size"]
        [::std::mem::offset_of!(lgw_conf_rxif_s, sync_word_size) - 16usize];
    ["Offset of field: lgw_conf_rxif_s::sync_word"]
        [::std::mem::offset_of!(lgw_conf_rxif_s, sync_word) - 24usize];
    ["Offset of field: lgw_conf_rxif_s::implicit_hdr"]
        [::std::mem::offset_of!(lgw_conf_rxif_s, implicit_hdr) - 32usize];
    ["Offset of field: lgw_conf_rxif_s::implicit_payload_length"]
        [::std::mem::offset_of!(lgw_conf_rxif_s, implicit_payload_length) - 33usize];
    ["Offset of field: lgw_conf_rxif_s::implicit_crc_en"]
        [::std::mem::offset_of!(lgw_conf_rxif_s, implicit_crc_en) - 34usize];
    ["Offset of field: lgw_conf_rxif_s::implicit_coderate"]
        [::std::mem::offset_of!(lgw_conf_rxif_s, implicit_coderate) - 35usize];
};
#[doc = "@struct lgw_conf_demod_s\n@brief Configuration structure for LoRa/FSK demodulators"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_conf_demod_s {
    pub multisf_datarate: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_conf_demod_s"][::std::mem::size_of::<lgw_conf_demod_s>() - 1usize];
    ["Alignment of lgw_conf_demod_s"][::std::mem::align_of::<lgw_conf_demod_s>() - 1usize];
    ["Offset of field: lgw_conf_demod_s::multisf_datarate"]
        [::std::mem::offset_of!(lgw_conf_demod_s, multisf_datarate) - 0usize];
};
#[doc = "@struct lgw_pkt_rx_s\n@brief Structure containing the metadata of a packet that was received and a pointer to the payload"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_pkt_rx_s {
    pub freq_hz: u32,
    #[doc = "> central frequency of the IF chain"]
    pub freq_offset: i32,
    pub if_chain: u8,
    #[doc = "> by which IF chain was packet received"]
    pub status: u8,
    #[doc = "> status of the received packet"]
    pub count_us: u32,
    #[doc = "> internal concentrator counter for timestamping, 1 microsecond resolution"]
    pub rf_chain: u8,
    #[doc = "> through which RF chain the packet was received"]
    pub modem_id: u8,
    pub modulation: u8,
    #[doc = "> modulation used by the packet"]
    pub bandwidth: u8,
    #[doc = "> modulation bandwidth (LoRa only)"]
    pub datarate: u32,
    #[doc = "> RX datarate of the packet (SF for LoRa)"]
    pub coderate: u8,
    #[doc = "> error-correcting code of the packet (LoRa only)"]
    pub rssic: f32,
    #[doc = "> average RSSI of the channel in dB"]
    pub rssis: f32,
    #[doc = "> average RSSI of the signal in dB"]
    pub snr: f32,
    #[doc = "> average packet SNR, in dB (LoRa only)"]
    pub snr_min: f32,
    #[doc = "> minimum packet SNR, in dB (LoRa only)"]
    pub snr_max: f32,
    #[doc = "> maximum packet SNR, in dB (LoRa only)"]
    pub crc: u16,
    #[doc = "> CRC that was received in the payload"]
    pub size: u16,
    #[doc = "> payload size in bytes"]
    pub payload: [u8; 256usize],
    #[doc = "> buffer containing the payload"]
    pub ftime_received: bool,
    #[doc = "> a fine timestamp has been received"]
    pub ftime: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_pkt_rx_s"][::std::mem::size_of::<lgw_pkt_rx_s>() - 316usize];
    ["Alignment of lgw_pkt_rx_s"][::std::mem::align_of::<lgw_pkt_rx_s>() - 4usize];
    ["Offset of field: lgw_pkt_rx_s::freq_hz"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, freq_hz) - 0usize];
    ["Offset of field: lgw_pkt_rx_s::freq_offset"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, freq_offset) - 4usize];
    ["Offset of field: lgw_pkt_rx_s::if_chain"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, if_chain) - 8usize];
    ["Offset of field: lgw_pkt_rx_s::status"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, status) - 9usize];
    ["Offset of field: lgw_pkt_rx_s::count_us"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, count_us) - 12usize];
    ["Offset of field: lgw_pkt_rx_s::rf_chain"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, rf_chain) - 16usize];
    ["Offset of field: lgw_pkt_rx_s::modem_id"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, modem_id) - 17usize];
    ["Offset of field: lgw_pkt_rx_s::modulation"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, modulation) - 18usize];
    ["Offset of field: lgw_pkt_rx_s::bandwidth"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, bandwidth) - 19usize];
    ["Offset of field: lgw_pkt_rx_s::datarate"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, datarate) - 20usize];
    ["Offset of field: lgw_pkt_rx_s::coderate"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, coderate) - 24usize];
    ["Offset of field: lgw_pkt_rx_s::rssic"][::std::mem::offset_of!(lgw_pkt_rx_s, rssic) - 28usize];
    ["Offset of field: lgw_pkt_rx_s::rssis"][::std::mem::offset_of!(lgw_pkt_rx_s, rssis) - 32usize];
    ["Offset of field: lgw_pkt_rx_s::snr"][::std::mem::offset_of!(lgw_pkt_rx_s, snr) - 36usize];
    ["Offset of field: lgw_pkt_rx_s::snr_min"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, snr_min) - 40usize];
    ["Offset of field: lgw_pkt_rx_s::snr_max"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, snr_max) - 44usize];
    ["Offset of field: lgw_pkt_rx_s::crc"][::std::mem::offset_of!(lgw_pkt_rx_s, crc) - 48usize];
    ["Offset of field: lgw_pkt_rx_s::size"][::std::mem::offset_of!(lgw_pkt_rx_s, size) - 50usize];
    ["Offset of field: lgw_pkt_rx_s::payload"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, payload) - 52usize];
    ["Offset of field: lgw_pkt_rx_s::ftime_received"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, ftime_received) - 308usize];
    ["Offset of field: lgw_pkt_rx_s::ftime"]
        [::std::mem::offset_of!(lgw_pkt_rx_s, ftime) - 312usize];
};
#[doc = "@struct lgw_pkt_tx_s\n@brief Structure containing the configuration of a packet to send and a pointer to the payload"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_pkt_tx_s {
    pub freq_hz: u32,
    #[doc = "> center frequency of TX"]
    pub tx_mode: u8,
    #[doc = "> select on what event/time the TX is triggered"]
    pub count_us: u32,
    #[doc = "> timestamp or delay in microseconds for TX trigger"]
    pub rf_chain: u8,
    #[doc = "> through which RF chain will the packet be sent"]
    pub rf_power: i8,
    #[doc = "> TX power, in dBm"]
    pub modulation: u8,
    #[doc = "> modulation to use for the packet"]
    pub freq_offset: i8,
    #[doc = "> frequency offset from Radio Tx frequency (CW mode)"]
    pub bandwidth: u8,
    #[doc = "> modulation bandwidth (LoRa only)"]
    pub datarate: u32,
    #[doc = "> TX datarate (baudrate for FSK, SF for LoRa)"]
    pub coderate: u8,
    #[doc = "> error-correcting code of the packet (LoRa only)"]
    pub invert_pol: bool,
    #[doc = "> invert signal polarity, for orthogonal downlinks (LoRa only)"]
    pub f_dev: u8,
    #[doc = "> frequency deviation, in kHz (FSK only)"]
    pub preamble: u16,
    #[doc = "> set the preamble length, 0 for default"]
    pub no_crc: bool,
    #[doc = "> if true, do not send a CRC in the packet"]
    pub no_header: bool,
    #[doc = "> if true, enable implicit header mode (LoRa), fixed length (FSK)"]
    pub size: u16,
    #[doc = "> payload size in bytes"]
    pub payload: [u8; 256usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_pkt_tx_s"][::std::mem::size_of::<lgw_pkt_tx_s>() - 292usize];
    ["Alignment of lgw_pkt_tx_s"][::std::mem::align_of::<lgw_pkt_tx_s>() - 4usize];
    ["Offset of field: lgw_pkt_tx_s::freq_hz"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, freq_hz) - 0usize];
    ["Offset of field: lgw_pkt_tx_s::tx_mode"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, tx_mode) - 4usize];
    ["Offset of field: lgw_pkt_tx_s::count_us"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, count_us) - 8usize];
    ["Offset of field: lgw_pkt_tx_s::rf_chain"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, rf_chain) - 12usize];
    ["Offset of field: lgw_pkt_tx_s::rf_power"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, rf_power) - 13usize];
    ["Offset of field: lgw_pkt_tx_s::modulation"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, modulation) - 14usize];
    ["Offset of field: lgw_pkt_tx_s::freq_offset"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, freq_offset) - 15usize];
    ["Offset of field: lgw_pkt_tx_s::bandwidth"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, bandwidth) - 16usize];
    ["Offset of field: lgw_pkt_tx_s::datarate"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, datarate) - 20usize];
    ["Offset of field: lgw_pkt_tx_s::coderate"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, coderate) - 24usize];
    ["Offset of field: lgw_pkt_tx_s::invert_pol"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, invert_pol) - 25usize];
    ["Offset of field: lgw_pkt_tx_s::f_dev"][::std::mem::offset_of!(lgw_pkt_tx_s, f_dev) - 26usize];
    ["Offset of field: lgw_pkt_tx_s::preamble"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, preamble) - 28usize];
    ["Offset of field: lgw_pkt_tx_s::no_crc"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, no_crc) - 30usize];
    ["Offset of field: lgw_pkt_tx_s::no_header"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, no_header) - 31usize];
    ["Offset of field: lgw_pkt_tx_s::size"][::std::mem::offset_of!(lgw_pkt_tx_s, size) - 32usize];
    ["Offset of field: lgw_pkt_tx_s::payload"]
        [::std::mem::offset_of!(lgw_pkt_tx_s, payload) - 34usize];
};
#[doc = "@struct lgw_tx_gain_s\n@brief Structure containing all gains of Tx chain"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_tx_gain_s {
    pub rf_power: i8,
    #[doc = "> measured TX power at the board connector, in dBm"]
    pub dig_gain: u8,
    #[doc = "> (sx125x) 2 bits: control of the digital gain of SX1302"]
    pub pa_gain: u8,
    #[doc = "> (sx125x) 2 bits: control of the external PA (SX1302 I/O)\n(sx1250) 1 bits: enable/disable the external PA (SX1302 I/O)"]
    pub dac_gain: u8,
    #[doc = "> (sx125x) 2 bits: control of the radio DAC"]
    pub mix_gain: u8,
    #[doc = "> (sx125x) 4 bits: control of the radio mixer"]
    pub offset_i: i8,
    #[doc = "> (sx125x) calibrated I offset"]
    pub offset_q: i8,
    #[doc = "> (sx125x) calibrated Q offset"]
    pub pwr_idx: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_tx_gain_s"][::std::mem::size_of::<lgw_tx_gain_s>() - 8usize];
    ["Alignment of lgw_tx_gain_s"][::std::mem::align_of::<lgw_tx_gain_s>() - 1usize];
    ["Offset of field: lgw_tx_gain_s::rf_power"]
        [::std::mem::offset_of!(lgw_tx_gain_s, rf_power) - 0usize];
    ["Offset of field: lgw_tx_gain_s::dig_gain"]
        [::std::mem::offset_of!(lgw_tx_gain_s, dig_gain) - 1usize];
    ["Offset of field: lgw_tx_gain_s::pa_gain"]
        [::std::mem::offset_of!(lgw_tx_gain_s, pa_gain) - 2usize];
    ["Offset of field: lgw_tx_gain_s::dac_gain"]
        [::std::mem::offset_of!(lgw_tx_gain_s, dac_gain) - 3usize];
    ["Offset of field: lgw_tx_gain_s::mix_gain"]
        [::std::mem::offset_of!(lgw_tx_gain_s, mix_gain) - 4usize];
    ["Offset of field: lgw_tx_gain_s::offset_i"]
        [::std::mem::offset_of!(lgw_tx_gain_s, offset_i) - 5usize];
    ["Offset of field: lgw_tx_gain_s::offset_q"]
        [::std::mem::offset_of!(lgw_tx_gain_s, offset_q) - 6usize];
    ["Offset of field: lgw_tx_gain_s::pwr_idx"]
        [::std::mem::offset_of!(lgw_tx_gain_s, pwr_idx) - 7usize];
};
#[doc = "@struct lgw_tx_gain_lut_s\n@brief Structure defining the Tx gain LUT"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_tx_gain_lut_s {
    pub lut: [lgw_tx_gain_s; 16usize],
    #[doc = "> Array of Tx gain struct"]
    pub size: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_tx_gain_lut_s"][::std::mem::size_of::<lgw_tx_gain_lut_s>() - 129usize];
    ["Alignment of lgw_tx_gain_lut_s"][::std::mem::align_of::<lgw_tx_gain_lut_s>() - 1usize];
    ["Offset of field: lgw_tx_gain_lut_s::lut"]
        [::std::mem::offset_of!(lgw_tx_gain_lut_s, lut) - 0usize];
    ["Offset of field: lgw_tx_gain_lut_s::size"]
        [::std::mem::offset_of!(lgw_tx_gain_lut_s, size) - 128usize];
};
#[doc = "@struct lgw_conf_debug_s\n@brief Configuration structure for debug"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct conf_ref_payload_s {
    pub id: u32,
    pub payload: [u8; 255usize],
    pub prev_cnt: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of conf_ref_payload_s"][::std::mem::size_of::<conf_ref_payload_s>() - 264usize];
    ["Alignment of conf_ref_payload_s"][::std::mem::align_of::<conf_ref_payload_s>() - 4usize];
    ["Offset of field: conf_ref_payload_s::id"]
        [::std::mem::offset_of!(conf_ref_payload_s, id) - 0usize];
    ["Offset of field: conf_ref_payload_s::payload"]
        [::std::mem::offset_of!(conf_ref_payload_s, payload) - 4usize];
    ["Offset of field: conf_ref_payload_s::prev_cnt"]
        [::std::mem::offset_of!(conf_ref_payload_s, prev_cnt) - 260usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_conf_debug_s {
    pub nb_ref_payload: u8,
    pub ref_payload: [conf_ref_payload_s; 16usize],
    pub log_file_name: [::std::os::raw::c_char; 128usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_conf_debug_s"][::std::mem::size_of::<lgw_conf_debug_s>() - 4356usize];
    ["Alignment of lgw_conf_debug_s"][::std::mem::align_of::<lgw_conf_debug_s>() - 4usize];
    ["Offset of field: lgw_conf_debug_s::nb_ref_payload"]
        [::std::mem::offset_of!(lgw_conf_debug_s, nb_ref_payload) - 0usize];
    ["Offset of field: lgw_conf_debug_s::ref_payload"]
        [::std::mem::offset_of!(lgw_conf_debug_s, ref_payload) - 4usize];
    ["Offset of field: lgw_conf_debug_s::log_file_name"]
        [::std::mem::offset_of!(lgw_conf_debug_s, log_file_name) - 4228usize];
};
pub const lgw_ftime_mode_t_LGW_FTIME_MODE_HIGH_CAPACITY: lgw_ftime_mode_t = 0;
#[doc = "> fine timestamps for SF5 -> SF10"]
pub const lgw_ftime_mode_t_LGW_FTIME_MODE_ALL_SF: lgw_ftime_mode_t = 1;
#[doc = "@enum lgw_ftime_mode_t\n@brief Fine timestamping modes"]
pub type lgw_ftime_mode_t = ::std::os::raw::c_uint;
#[doc = "@struct lgw_conf_ftime_s\n@brief Configuration structure for fine timestamping"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_conf_ftime_s {
    pub enable: bool,
    #[doc = "> Enable / Disable fine timestamping"]
    pub mode: lgw_ftime_mode_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_conf_ftime_s"][::std::mem::size_of::<lgw_conf_ftime_s>() - 8usize];
    ["Alignment of lgw_conf_ftime_s"][::std::mem::align_of::<lgw_conf_ftime_s>() - 4usize];
    ["Offset of field: lgw_conf_ftime_s::enable"]
        [::std::mem::offset_of!(lgw_conf_ftime_s, enable) - 0usize];
    ["Offset of field: lgw_conf_ftime_s::mode"]
        [::std::mem::offset_of!(lgw_conf_ftime_s, mode) - 4usize];
};
pub const lgw_lbt_scan_time_t_LGW_LBT_SCAN_TIME_128_US: lgw_lbt_scan_time_t = 128;
pub const lgw_lbt_scan_time_t_LGW_LBT_SCAN_TIME_5000_US: lgw_lbt_scan_time_t = 5000;
#[doc = "@enum lgw_lbt_scan_time_t\n@brief Radio types that can be found on the LoRa Gateway"]
pub type lgw_lbt_scan_time_t = ::std::os::raw::c_uint;
#[doc = "@brief Structure containing a Listen-Before-Talk channel configuration"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_conf_chan_lbt_s {
    pub freq_hz: u32,
    #[doc = "> LBT channel frequency"]
    pub bandwidth: u8,
    #[doc = "> LBT channel bandwidth"]
    pub scan_time_us: lgw_lbt_scan_time_t,
    #[doc = "> LBT channel carrier sense time"]
    pub transmit_time_ms: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_conf_chan_lbt_s"][::std::mem::size_of::<lgw_conf_chan_lbt_s>() - 16usize];
    ["Alignment of lgw_conf_chan_lbt_s"][::std::mem::align_of::<lgw_conf_chan_lbt_s>() - 4usize];
    ["Offset of field: lgw_conf_chan_lbt_s::freq_hz"]
        [::std::mem::offset_of!(lgw_conf_chan_lbt_s, freq_hz) - 0usize];
    ["Offset of field: lgw_conf_chan_lbt_s::bandwidth"]
        [::std::mem::offset_of!(lgw_conf_chan_lbt_s, bandwidth) - 4usize];
    ["Offset of field: lgw_conf_chan_lbt_s::scan_time_us"]
        [::std::mem::offset_of!(lgw_conf_chan_lbt_s, scan_time_us) - 8usize];
    ["Offset of field: lgw_conf_chan_lbt_s::transmit_time_ms"]
        [::std::mem::offset_of!(lgw_conf_chan_lbt_s, transmit_time_ms) - 12usize];
};
#[doc = "@struct lgw_conf_lbt_s\n@brief Configuration structure for listen-before-talk"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_conf_lbt_s {
    pub enable: bool,
    #[doc = "> enable or disable LBT"]
    pub rssi_target: i8,
    #[doc = "> RSSI threshold to detect if channel is busy or not (dBm)"]
    pub nb_channel: u8,
    #[doc = "> number of LBT channels"]
    pub channels: [lgw_conf_chan_lbt_s; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_conf_lbt_s"][::std::mem::size_of::<lgw_conf_lbt_s>() - 260usize];
    ["Alignment of lgw_conf_lbt_s"][::std::mem::align_of::<lgw_conf_lbt_s>() - 4usize];
    ["Offset of field: lgw_conf_lbt_s::enable"]
        [::std::mem::offset_of!(lgw_conf_lbt_s, enable) - 0usize];
    ["Offset of field: lgw_conf_lbt_s::rssi_target"]
        [::std::mem::offset_of!(lgw_conf_lbt_s, rssi_target) - 1usize];
    ["Offset of field: lgw_conf_lbt_s::nb_channel"]
        [::std::mem::offset_of!(lgw_conf_lbt_s, nb_channel) - 2usize];
    ["Offset of field: lgw_conf_lbt_s::channels"]
        [::std::mem::offset_of!(lgw_conf_lbt_s, channels) - 4usize];
};
#[doc = "@struct lgw_conf_sx1261_s\n@brief Configuration structure for additional SX1261 radio used for LBT and Spectral Scan"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_conf_sx1261_s {
    pub enable: bool,
    #[doc = "> enable or disable SX1261 radio"]
    pub spi_path: [::std::os::raw::c_char; 64usize],
    #[doc = "> Path to access the SPI device to connect to the SX1261 (not used for USB com type)"]
    pub rssi_offset: i8,
    #[doc = "> value to be applied to the sx1261 RSSI value (dBm)"]
    pub lbt_conf: lgw_conf_lbt_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_conf_sx1261_s"][::std::mem::size_of::<lgw_conf_sx1261_s>() - 328usize];
    ["Alignment of lgw_conf_sx1261_s"][::std::mem::align_of::<lgw_conf_sx1261_s>() - 4usize];
    ["Offset of field: lgw_conf_sx1261_s::enable"]
        [::std::mem::offset_of!(lgw_conf_sx1261_s, enable) - 0usize];
    ["Offset of field: lgw_conf_sx1261_s::spi_path"]
        [::std::mem::offset_of!(lgw_conf_sx1261_s, spi_path) - 1usize];
    ["Offset of field: lgw_conf_sx1261_s::rssi_offset"]
        [::std::mem::offset_of!(lgw_conf_sx1261_s, rssi_offset) - 65usize];
    ["Offset of field: lgw_conf_sx1261_s::lbt_conf"]
        [::std::mem::offset_of!(lgw_conf_sx1261_s, lbt_conf) - 68usize];
};
#[doc = "@struct lgw_context_s\n@brief Configuration context shared across modules"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lgw_context_s {
    pub is_started: bool,
    pub board_cfg: lgw_conf_board_s,
    pub rf_chain_cfg: [lgw_conf_rxrf_s; 2usize],
    pub if_chain_cfg: [lgw_conf_rxif_s; 10usize],
    pub demod_cfg: lgw_conf_demod_s,
    pub lora_service_cfg: lgw_conf_rxif_s,
    pub fsk_cfg: lgw_conf_rxif_s,
    pub tx_gain_lut: [lgw_tx_gain_lut_s; 2usize],
    pub ftime_cfg: lgw_conf_ftime_s,
    pub sx1261_cfg: lgw_conf_sx1261_s,
    pub debug_cfg: lgw_conf_debug_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lgw_context_s"][::std::mem::size_of::<lgw_context_s>() - 5600usize];
    ["Alignment of lgw_context_s"][::std::mem::align_of::<lgw_context_s>() - 8usize];
    ["Offset of field: lgw_context_s::is_started"]
        [::std::mem::offset_of!(lgw_context_s, is_started) - 0usize];
    ["Offset of field: lgw_context_s::board_cfg"]
        [::std::mem::offset_of!(lgw_context_s, board_cfg) - 4usize];
    ["Offset of field: lgw_context_s::rf_chain_cfg"]
        [::std::mem::offset_of!(lgw_context_s, rf_chain_cfg) - 76usize];
    ["Offset of field: lgw_context_s::if_chain_cfg"]
        [::std::mem::offset_of!(lgw_context_s, if_chain_cfg) - 160usize];
    ["Offset of field: lgw_context_s::demod_cfg"]
        [::std::mem::offset_of!(lgw_context_s, demod_cfg) - 560usize];
    ["Offset of field: lgw_context_s::lora_service_cfg"]
        [::std::mem::offset_of!(lgw_context_s, lora_service_cfg) - 568usize];
    ["Offset of field: lgw_context_s::fsk_cfg"]
        [::std::mem::offset_of!(lgw_context_s, fsk_cfg) - 608usize];
    ["Offset of field: lgw_context_s::tx_gain_lut"]
        [::std::mem::offset_of!(lgw_context_s, tx_gain_lut) - 648usize];
    ["Offset of field: lgw_context_s::ftime_cfg"]
        [::std::mem::offset_of!(lgw_context_s, ftime_cfg) - 908usize];
    ["Offset of field: lgw_context_s::sx1261_cfg"]
        [::std::mem::offset_of!(lgw_context_s, sx1261_cfg) - 916usize];
    ["Offset of field: lgw_context_s::debug_cfg"]
        [::std::mem::offset_of!(lgw_context_s, debug_cfg) - 1244usize];
};
#[doc = "@struct lgw_context_s\n@brief Configuration context shared across modules"]
pub type lgw_context_t = lgw_context_s;
pub const lgw_spectral_scan_status_e_LGW_SPECTRAL_SCAN_STATUS_NONE: lgw_spectral_scan_status_e = 0;
pub const lgw_spectral_scan_status_e_LGW_SPECTRAL_SCAN_STATUS_ON_GOING: lgw_spectral_scan_status_e =
    1;
pub const lgw_spectral_scan_status_e_LGW_SPECTRAL_SCAN_STATUS_ABORTED: lgw_spectral_scan_status_e =
    2;
pub const lgw_spectral_scan_status_e_LGW_SPECTRAL_SCAN_STATUS_COMPLETED:
    lgw_spectral_scan_status_e = 3;
pub const lgw_spectral_scan_status_e_LGW_SPECTRAL_SCAN_STATUS_UNKNOWN: lgw_spectral_scan_status_e =
    4;
#[doc = "@struct lgw_spectral_scan_status_t\n@brief Spectral Scan status"]
pub type lgw_spectral_scan_status_e = ::std::os::raw::c_uint;
#[doc = "@struct lgw_spectral_scan_status_t\n@brief Spectral Scan status"]
pub use self::lgw_spectral_scan_status_e as lgw_spectral_scan_status_t;
unsafe extern "C" {
    #[doc = "@brief Configure the gateway board\n@param conf structure containing the configuration parameters\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_board_setconf(conf: *mut lgw_conf_board_s) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Configure an RF chain (must configure before start)\n@param rf_chain number of the RF chain to configure [0, LGW_RF_CHAIN_NB - 1]\n@param conf structure containing the configuration parameters\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_rxrf_setconf(rf_chain: u8, conf: *mut lgw_conf_rxrf_s) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Configure an IF chain + modem (must configure before start)\n@param if_chain number of the IF chain + modem to configure [0, LGW_IF_CHAIN_NB - 1]\n@param conf structure containing the configuration parameters\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_rxif_setconf(if_chain: u8, conf: *mut lgw_conf_rxif_s) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Configure LoRa/FSK demodulators\n@param conf structure containing the configuration parameters\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_demod_setconf(conf: *mut lgw_conf_demod_s) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Configure the Tx gain LUT\n@param conf pointer to structure defining the LUT\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_txgain_setconf(rf_chain: u8, conf: *mut lgw_tx_gain_lut_s) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Configure the fine timestamping\n@param conf pointer to structure defining the config to be applied\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_ftime_setconf(conf: *mut lgw_conf_ftime_s) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lgw_sx1261_setconf(conf: *mut lgw_conf_sx1261_s) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Configure the debug context\n@param conf pointer to structure defining the config to be applied\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_debug_setconf(conf: *mut lgw_conf_debug_s) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Connect to the LoRa concentrator, reset it and configure it according to previously set parameters\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_start() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Stop the LoRa concentrator and disconnect it\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_stop() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief A non-blocking function that will fetch up to 'max_pkt' packets from the LoRa concentrator FIFO and data buffer\n@param max_pkt maximum number of packet that must be retrieved (equal to the size of the array of struct)\n@param pkt_data pointer to an array of struct that will receive the packet metadata and payload pointers\n@return LGW_HAL_ERROR id the operation failed, else the number of packets retrieved"]
    pub fn lgw_receive(max_pkt: u8, pkt_data: *mut lgw_pkt_rx_s) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Schedule a packet to be send immediately or after a delay depending on tx_mode\n@param pkt_data structure containing the data and metadata for the packet to send\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else\n\n/!\\ When sending a packet, there is a delay (approx 1.5ms) for the analog\ncircuitry to start and be stable. This delay is adjusted by the HAL depending\non the board version (lgw_i_tx_start_delay_us).\n\nIn 'timestamp' mode, this is transparent: the modem is started\nlgw_i_tx_start_delay_us microseconds before the user-set timestamp value is\nreached, the preamble of the packet start right when the internal timestamp\ncounter reach target value.\n\nIn 'immediate' mode, the packet is emitted as soon as possible: transferring the\npacket (and its parameters) from the host to the concentrator takes some time,\nthen there is the lgw_i_tx_start_delay_us, then the packet is emitted.\n\nIn 'triggered' mode (aka PPS/GPS mode), the packet, typically a beacon, is\nemitted lgw_i_tx_start_delay_us microsenconds after a rising edge of the\ntrigger signal. Because there is no way to anticipate the triggering event and\nstart the analog circuitry beforehand, that delay must be taken into account in\nthe protocol."]
    pub fn lgw_send(pkt_data: *mut lgw_pkt_tx_s) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Give the the status of different part of the LoRa concentrator\n@param select is used to select what status we want to know\n@param code is used to return the status code\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_status(rf_chain: u8, select: u8, code: *mut u8) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Abort a currently scheduled or ongoing TX\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_abort_tx(rf_chain: u8) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Return value of internal counter when latest event (eg GPS pulse) was captured\n@param trig_cnt_us pointer to receive timestamp value\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_get_trigcnt(trig_cnt_us: *mut u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Return instateneous value of internal counter\n@param inst_cnt_us pointer to receive timestamp value\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_get_instcnt(inst_cnt_us: *mut u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Return the LoRa concentrator EUI\n@param eui pointer to receive eui\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_get_eui(eui: *mut u64) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Return the temperature measured by the LoRa concentrator sensor\n@param temperature The temperature measured, in degree celcius\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_get_temperature(temperature: *mut f32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Allow user to check the version/options of the library once compiled\n@return pointer on a human-readable null terminated string"]
    pub fn lgw_version_info() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = "@brief Return time on air of given packet, in milliseconds\n@param packet is a pointer to the packet structure\n@return the packet time on air in milliseconds"]
    pub fn lgw_time_on_air(packet: *const lgw_pkt_tx_s) -> u32;
}
unsafe extern "C" {
    #[doc = "@brief Start scaning the channel centered on the given frequency\n@param freq_hz channel center frequency\n@param nb_scan number of measures to be done for the scan\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_spectral_scan_start(freq_hz: u32, nb_scan: u16) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Get the current scan status\n@param status a pointer to the returned status\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_spectral_scan_get_status(
        status: *mut lgw_spectral_scan_status_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Get the channel scan results\n@param levels an array containing the power levels for which the scan results are given\n@param values ar array containing the results of the scan for each power levels\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_spectral_scan_get_results(
        levels_dbm: *mut i16,
        results: *mut u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Abort the current scan\n@return LGW_HAL_ERROR id the operation failed, LGW_HAL_SUCCESS else"]
    pub fn lgw_spectral_scan_abort() -> ::std::os::raw::c_int;
}
